In [11]:
import pandas as pd
import numpy as np
from sklearn import decomposition
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

import matplotlib.pyplot as plt

In [2]:
df_work = pd.read_csv('datasets/candidatos_work.csv', sep=';')
df_work.drop(['composicao_legenda'],axis=1, inplace=True)
df_work.head()

grau_instrucao  nacionalidade  concorre_reeleicao  declara_bens  \
0               6              1                   0             0   
1               8              1                   0             1   
2               8              1                   0             1   
3               6              1                   0             1   
4               8              1                   0             0   

   despesa_maxima_campanha  idade_data_posse  eleito  cor_raca_AMARELA  \
0                 400000.0              45.0       0                 0   
1                1000000.0              50.0       0                 0   
2                 690000.0              48.0       0                 0   
3                 500000.0              39.0       0                 0   
4                 500000.0              40.0       0                 0   

   cor_raca_BRANCA  cor_raca_INDIGENA       ...        \
0                0                  0       ...         
1                1                  0       ...         
2                0                  0       ...         
3                0                  0       ...         
4                0                  0       ...         

   cargo_1o SUPLENTE SENADOR  cargo_2o SUPLENTE SENADOR  \
0                          0                          0   
1                          0                          0   
2                          0                          0   
3                          0                          0   
4                          0                          0   

   cargo_DEPUTADO DISTRITAL  cargo_DEPUTADO ESTADUAL  cargo_DEPUTADO FEDERAL  \
0                         0                        1                       0   
1                         0                        1                       0   
2                         0                        1                       0   
3                         0                        1                       0   
4                         0                        1                       0   

   cargo_GOVERNADOR  cargo_PREFEITO  cargo_PRESIDENTE  cargo_SENADOR  \
0                 0               0                 0              0   
1                 0               0                 0              0   
2                 0               0                 0              0   
3                 0               0                 0              0   
4                 0               0                 0              0   

   cargo_VEREADOR  
0               0  
1               0  
2               0  
3               0  
4               0  

[5 rows x 309 columns]

In [3]:
df_data = df_work.drop(['eleito'], axis=1)
df_labels = df_work.loc[:,['eleito']].values.ravel()
df_data.head()

grau_instrucao  nacionalidade  concorre_reeleicao  declara_bens  \
0               6              1                   0             0   
1               8              1                   0             1   
2               8              1                   0             1   
3               6              1                   0             1   
4               8              1                   0             0   

   despesa_maxima_campanha  idade_data_posse  cor_raca_AMARELA  \
0                 400000.0              45.0                 0   
1                1000000.0              50.0                 0   
2                 690000.0              48.0                 0   
3                 500000.0              39.0                 0   
4                 500000.0              40.0                 0   

   cor_raca_BRANCA  cor_raca_INDIGENA  cor_raca_PARDA       ...        \
0                0                  0               0       ...         
1                1                  0               0       ...         
2                0                  0               1       ...         
3                0                  0               1       ...         
4                0                  0               1       ...         

   cargo_1o SUPLENTE SENADOR  cargo_2o SUPLENTE SENADOR  \
0                          0                          0   
1                          0                          0   
2                          0                          0   
3                          0                          0   
4                          0                          0   

   cargo_DEPUTADO DISTRITAL  cargo_DEPUTADO ESTADUAL  cargo_DEPUTADO FEDERAL  \
0                         0                        1                       0   
1                         0                        1                       0   
2                         0                        1                       0   
3                         0                        1                       0   
4                         0                        1                       0   

   cargo_GOVERNADOR  cargo_PREFEITO  cargo_PRESIDENTE  cargo_SENADOR  \
0                 0               0                 0              0   
1                 0               0                 0              0   
2                 0               0                 0              0   
3                 0               0                 0              0   
4                 0               0                 0              0   

   cargo_VEREADOR  
0               0  
1               0  
2               0  
3               0  
4               0  

[5 rows x 308 columns]

In [4]:
unique_elements, counts_elements = np.unique(df_labels, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Frequency of unique values of the said array:
[[     0      1]
 [434685  66819]]


In [6]:
np_scaled = StandardScaler().fit_transform(df_data)
df_scaled = pd.DataFrame(np_scaled, index=df_data.index, columns=df_data.columns)
df_scaled.head()

c:\users\yami_\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
c:\users\yami_\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


grau_instrucao  nacionalidade  concorre_reeleicao  declara_bens  \
0        0.186152       -0.05375           -0.325391     -1.351565   
1        1.313575       -0.05375           -0.325391      0.739883   
2        1.313575       -0.05375           -0.325391      0.739883   
3        0.186152       -0.05375           -0.325391      0.739883   
4        1.313575       -0.05375           -0.325391     -1.351565   

   despesa_maxima_campanha  idade_data_posse  cor_raca_AMARELA  \
0                 0.213799          0.008173         -0.066394   
1                 0.678450          0.442036         -0.066394   
2                 0.438381          0.268490         -0.066394   
3                 0.291241         -0.512463         -0.066394   
4                 0.291241         -0.425690         -0.066394   

   cor_raca_BRANCA  cor_raca_INDIGENA  cor_raca_PARDA       ...        \
0        -1.032355          -0.058613       -0.795980       ...         
1         0.968659          -0.058613       -0.795980       ...         
2        -1.032355          -0.058613        1.256312       ...         
3        -1.032355          -0.058613        1.256312       ...         
4        -1.032355          -0.058613        1.256312       ...         

   cargo_1o SUPLENTE SENADOR  cargo_2o SUPLENTE SENADOR  \
0                  -0.031177                  -0.031209   
1                  -0.031177                  -0.031209   
2                  -0.031177                  -0.031209   
3                  -0.031177                  -0.031209   
4                  -0.031177                  -0.031209   

   cargo_DEPUTADO DISTRITAL  cargo_DEPUTADO ESTADUAL  cargo_DEPUTADO FEDERAL  \
0                 -0.061636                 3.914173               -0.167636   
1                 -0.061636                 3.914173               -0.167636   
2                 -0.061636                 3.914173               -0.167636   
3                 -0.061636                 3.914173               -0.167636   
4                 -0.061636                 3.914173               -0.167636   

   cargo_GOVERNADOR  cargo_PREFEITO  cargo_PRESIDENTE  cargo_SENADOR  \
0         -0.026653       -0.180196           -0.0072      -0.031209   
1         -0.026653       -0.180196           -0.0072      -0.031209   
2         -0.026653       -0.180196           -0.0072      -0.031209   
3         -0.026653       -0.180196           -0.0072      -0.031209   
4         -0.026653       -0.180196           -0.0072      -0.031209   

   cargo_VEREADOR  
0       -2.615722  
1       -2.615722  
2       -2.615722  
3       -2.615722  
4       -2.615722  

[5 rows x 308 columns]

In [7]:
data_train, data_test, labels_train, labels_test = train_test_split(df_scaled, df_labels, test_size=0.2)

In [8]:
pca = decomposition.PCA(n_components=2)
pca_columns=['Component_1', 'Component_2']

data_train_pca = pd.DataFrame(pca.fit_transform(data_train), index=data_train.index, columns=pca_columns)
data_test_pca = pd.DataFrame(pca.transform(data_test), index=data_test.index, columns=pca_columns)

print(pca.explained_variance_ratio_[0])
print(pca.explained_variance_ratio_[1])
# print(pca.explained_variance_ratio_[2])
# print(pca.explained_variance_ratio_[3])
# print(pca.explained_variance_ratio_[4])
# print(pca.explained_variance_ratio_[5])
# print(pca.explained_variance_ratio_[6])
# print(pca.explained_variance_ratio_[7])
# print(pca.explained_variance_ratio_[8])
# print(pca.explained_variance_ratio_[9])

0.009356313379393662
0.007995482161568422


## Multilayer Perceptron

In [9]:
mlpc = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
mlpc.fit(data_train_pca, labels_train)
mlpc_pred = mlpc.predict(data_test_pca)

In [10]:
unique_elements, counts_elements = np.unique(mlpc_pred, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Frequency of unique values of the said array:
[[    0     1]
 [95853  4448]]


In [12]:
mlpc_accuracy = accuracy_score(labels_test, mlpc_pred)
mlpc_precision = precision_score(labels_test, mlpc_pred, average='macro')
mlpc_recall = recall_score(labels_test, mlpc_pred, average='macro')
mlpc_f1 = f1_score(labels_test, mlpc_pred, average='macro')
mlpc_cm = confusion_matrix(labels_test, mlpc_pred)

print("Accuracy is {}%".format(mlpc_accuracy * 100))
print("Precision is {}%".format(mlpc_precision * 100))
print("Recall is {}%".format(mlpc_recall * 100))
print("F-1 is {}%".format(mlpc_f1 * 100))
print(mlpc_cm)

Accuracy is 87.00312060697301%
Precision is 71.34319832012703%
Recall is 57.81152785504741%
F-1 is 59.92611462810486%
[[84856  2039]
 [10997  2409]]


## Random Forest Classifier

In [13]:
rfc = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=0)
rfc.fit(data_train_pca, labels_train)
rfc_pred = rfc.predict(data_test_pca)

In [14]:
unique_elements, counts_elements = np.unique(rfc_pred, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Frequency of unique values of the said array:
[[     0]
 [100301]]


## SVM

In [ ]:
svmc = SVC(gamma='scale')
svmc.fit(data_train_pca, labels_train)
svmc_pred = svmc.predict(data_test_pca)

In [ ]:
unique_elements, counts_elements = np.unique(svmc_pred, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))